- incubator/java-spring-boot2/README.md
Updated readme to clearly specify the endpoints provided by the stack/template
> doc: Updated java-spring-boot2 stack readme

- incubator/nodejs-express/README.md
docs: Updates nodejs-express stack readme
> doc: Updates nodejs-express stack readme

- incubator/nodejs/README.md
- index.yaml
Updated readme for nodejs stack
> doc: Updated nodejs stack readme

- incubator/java-microprofile/README.md
Overall re-write of the readme
> doc: Updated java-microprofile stack readme

- incubator/java-microprofile/image/Dockerfile-stack
java-microprofile: update stack to recompile on change for run/debug
> java-microprofile: update stack to recompile on change for run/debug

- incubator/nodejs-express/stack.yaml
Changed `aplicaiton` to `application`
Signed-off-by: bharathappali <bharath.appali@gmail.com>
> minor typo fix in incubator/nodejs-express/stack.yaml

- index.yaml
Updating  index to use spring template to 0.2.1
> Updating index to use spring template to 0.2.1

- .gitignore
- incubator/java-spring-boot2/README.md
- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/.appsody-init.bat
- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/Dockerfile
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/.appsody-config.yaml
- incubator/java-spring-boot2/templates/default/.gitignore
- incubator/java-spring-boot2/templates/default/pom.xml
> [java-spring-boot2]: Fix version update 

- index.yaml
Updated index to align/simplify template releases
> updated index to point to new release for each stack

- incubator/java-microprofile/README.md
This resolves https://github.com/appsody/website/issues/37
> Update README to recommend maven dependency for IDE experience

- incubator/nodejs-express/templates/simple/app.js
This does not fix a particular issue, but makes the hello message for node-express consistent with the proposed changes to java-microprofile and java-spring-boot2
> [node-express]: Set the hello world message to be "Hello from Appsody!"

- index.yaml
- Added appmetrics-dash to nodejs
- Added appmetrics-dash to nodejs-express
> Updating nodejs and nodejs-express stacks to 0.2.1

- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/default/src/main/resources/public/index.html
> [java-spring-boot2:0.3.1] Add index.html

- index.yaml
- Removed relativePath for parent pom as that was redundant
- renamed enforce.sh to validate.sh
> java-microprofile: Updated index for java-microprofile 0.2.1

- incubator/java-microprofile/README.md
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
Fixes #
> update Microprofile to MicroProfile

- README.md
- TECHNICAL_REQUIREMENTS.md
Fixes https://github.com/appsody/stacks/issues/64
Updated broken links that pointed to the deprecated docs repo.
> README: links updated

- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/.appsody-config.yaml
- incubator/java-microprofile/templates/default/pom.xml
- incubator/java-microprofile/templates/default/src/main/webapp/index.html
- Added blank relativePath
- Updated index content
Signed-off-by Neeraj Laad neeraj.laad@gmail.com
> java-microprofile: Updated relativePath, index content, version

- index.yaml
Signed-off-by Neeraj Laad neeraj.laad@gmail.com
Fixes #
> Updates index.yaml for java-microprofile 0.2.2

- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/templates/default/pom.xml
Signed-off-by Neeraj Laad neeraj.laad@gmail.com
Fixes #
> updated relativePath

- .github/PULL_REQUEST_TEMPLATE.md
> pull-template: improve readability of template

- index.yaml
Signed-off-by Neeraj Laad neeraj.laad@gmail.com
> Add swift to index

- incubator/swift/README.md
> README: making the readme for clarity

- incubator/nodejs/README.md
Fixes https://github.com/appsody/stacks/issues/87
Updated node.js stack README
> README.md: node.js stack updated

- experimental/nodejs-functions/LICENSE
- experimental/nodejs-functions/README.md
- experimental/nodejs-functions/image/.dockerignore
- experimental/nodejs-functions/image/Dockerfile-stack
- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/image/project/server.js
- experimental/nodejs-functions/image/project/test/test.js
- experimental/nodejs-functions/stack.yaml
- experimental/nodejs-functions/templates/simple/.appsody-config.yaml
- experimental/nodejs-functions/templates/simple/.vscode/launch.json
- experimental/nodejs-functions/templates/simple/.vscode/tasks.json
- experimental/nodejs-functions/templates/simple/function.js
- experimental/nodejs-functions/templates/simple/package.json
Fixes # NA
**Please provide the following in as much detail as you can:**
**Provide usage of the Appsody controller:**
This inherits the lifecycle from the underlying `nodejs` and `nodesjs-express` stacks, which this extends.
**Explain your rationale behind mount points:**
As this extends the `nodejs` and `nodejs-express` stacks, this provides a server.js file that goes into `/project/user-app` as would be expected of a `nodejs-express`, and then mounts the users functions into `/project/user-app/functions.`
The `server.js` file provided by this stack dynamically loads any files in the developers project that:
* has a `.js` suffix
* exports a `url` symbol
* exports a function using a symbol which is a HTTP verb (eg. `get`)
These are there added to the Express.js `app` object, which is …
> [nodejs-functions] Add initial implementation of 'nodejs-functions'

- experimental/nodejs-functions/stack.yaml
- incubator/java-microprofile/stack.yaml
- incubator/java-spring-boot2/stack.yaml
- incubator/nodejs-express/stack.yaml
- incubator/nodejs/stack.yaml
- incubator/swift/stack.yaml
- samples/sample-stack/stack.yaml
Updates.stack.yaml to newer format
Signed-off-by: Neeraj Laad neeraj.laad@gmail.com
Updated all stack.yaml files to match new format
Fixes #62
> Updated stack.yaml for all stacks

- incubator/java-microprofile/templates/default/src/main/webapp/index.html
> Fixing typo

- incubator/nodejs-express/image/project/Dockerfile
- incubator/nodejs-express/stack.yaml
> nodejs-express: expose PORT on production Dockerfile

- index.yaml
Updated index for following stacks:
- nodejs
- nodejs-express
- java-spring-boot2
> Updating index with new releases

- ci/package.sh
Updates release template name to match previous releases
> updated archive name to match previosu releases

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
upgrading open liberty version to 19.0.0.7 (latest)
> java-microprofile: upgrading openliberty version to 19.0.0.7

- index.yaml
Updated index for java-microprofile-v0.2.4 release
> Updated index for java-microprofile-v0.2.4

- ci/package.sh
- ci/release.sh
Updated the indexes to release v2 indexes and test index to match v2 format
> Updates to release v2 indexes

- experimental/quarkus/README.md
Updating the quarkus readme to include the known issues.
> quarkus-stack: adding known issues

- experimental/quarkus/README.md
> quarkus: formatting error

- ci/package.sh
signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>
> ci: test index should have local urls

- ci/release.sh
The `release.sh` script will now release the stacks during the release-build stage
> travisRelease: adding docker push capability

- ci/list.sh
- incubator/nodejs/stack.yaml
This PR fixes the issue where all the stacks are built when you push new changes to a stacks PR.
It now checks whether it is a PR or a commit.
Fixes: https://github.com/appsody/stacks/issues/141
> travis-ci: fixes bug for commits on PRs

- experimental/nodejs-functions/README.md
- experimental/quarkus/README.md
updating the experimental readme's so that users can use the experimental stacks
Fixes: https://github.com/appsody/stacks/issues/156
> experimental-stacks: updating run commands

- .gitignore
- ci/package.sh
> ci: update release script for local dev/test

- incubator/java-microprofile/README.md
- incubator/java-microprofile/templates/default/pom.xml
- incubator/java-microprofile/templates/default/src/main/java/dev/appsody/starter/health/StarterLivenessCheck.java
- incubator/java-microprofile/templates/default/src/main/java/dev/appsody/starter/health/StarterReadinessCheck.java
- incubator/java-microprofile/templates/default/src/main/liberty/config/server.xml
- incubator/java-microprofile/templates/default/src/test/java/it/dev/appsody/starter/HealthEndpointTest.java
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
> #148 Update appsody MicroProfile template to MP 3.0

- index.yaml
- updated java-microprofile 0.2.5
> stack-index: uopdated v1 index

- ci/build.sh
- ci/env.sh
- ci/list.sh
- ci/package.sh
- ci/release.sh
- ci/test.sh
Added ability for users to set environment variables before running appsody stacks build scripts.
Fixes: https://github.com/appsody/appsody/issues/166
> ci: allow users to override env vars

- experimental/nodejs-functions/templates/simple/package.json
This stack has recently been bumped to **0.1.1**. This PR updates the version in the package.json to match
> nodejs-functions: bump version

- experimental/quarkus/image/project/pom.xml
- experimental/quarkus/stack.yaml
- experimental/quarkus/templates/default/.appsody-config.yaml
- experimental/quarkus/templates/default/pom.xml
Adjusted config.yaml for the quarkus stack to point to the correct image.
Fixes: #175
> quarkus: adjusted config.yaml to point to the correct image

- RELEASE.md
Updated release.md to include sections about env.sh and create_codewind_index.py
Related to : #161
> doc: updated release process

- index.yaml
Updated v1 index for swift-v0.1.1 stack release
> swift: updated v1 index for stack release

- incubator/java-microprofile/image/Dockerfile-stack
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
Fixes: https://github.com/appsody/stacks/issues/45
> microprofile: adjusted to watch for xml and java files

- ci/create_codewind_index.py
- experimental/nodejs-functions/stack.yaml
- experimental/quarkus/stack.yaml
- incubator/java-microprofile/stack.yaml
- incubator/java-spring-boot2/stack.yaml
- incubator/nodejs-express/stack.yaml
- incubator/nodejs/stack.yaml
- incubator/swift/stack.yaml
- samples/sample-stack/stack.yaml
Added language field (for Codewind) to the `stack.yaml` file for all stacks
Related to: #161
> stacks: added language field

- ci/package.sh
- ci/release.sh
- removed v1 index that we are not using
- renamed test index to local index (helps local dev/test)
> ci: updated assets generated

- experimental/java-spring-boot2-liberty/LICENSE
- experimental/java-spring-boot2-liberty/README.md
- experimental/java-spring-boot2-liberty/image/.dockerignore
- experimental/java-spring-boot2-liberty/image/Dockerfile-stack
- experimental/java-spring-boot2-liberty/image/project/.appsody-init.bat
- experimental/java-spring-boot2-liberty/image/project/.appsody-init.sh
- experimental/java-spring-boot2-liberty/image/project/.dockerignore
- experimental/java-spring-boot2-liberty/image/project/Dockerfile
- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/image/project/stack.properties
- experimental/java-spring-boot2-liberty/image/project/validate.sh
- experimental/java-spring-boot2-liberty/stack.yaml
- experimental/java-spring-boot2-liberty/templates/default/.appsody-config.yaml
- experimental/java-spring-boot2-liberty/templates/default/.gitignore
- experimental/java-spring-boot2-liberty/templates/default/pom.xml
- experimental/java-spring-boot2-liberty/templates/default/src/main/java/application/Main.java
- experimental/java-spring-boot2-liberty/templates/default/src/main/liberty/config/server.xml
- experimental/java-spring-boot2-liberty/templates/default/src/main/resources/application.properties
- experimental/java-spring-boot2-liberty/templates/default/src/main/resources/public/index.html
- experimental/java-spring-boot2-liberty/templates/default/src/test/java/application/MainTests.java
Hybrid of Spring & Microprofile stack, to offer Spring on Liberty.
TBD
n/a
Tested as far as `appsody init` and `appsody run`, more to follow.
> Experimental Spring/Liberty Stack

- RELEASE.md
Updated release.md to clarify only Incubator stacks need updating in the v1 index.
> release.md: update v1 index para

- experimental/nodejs-loopback/stack.yaml
Signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>
remove id field from stack.yaml
> nodejs-loopback: remove id from stack.yaml

- experimental/java-spring-boot2-liberty/stack.yaml
- incubator/java-microprofile/stack.yaml
> Consistency updates to Stack descriptions where Open Liberty is used

- index.yaml
Updated v1 index for new spring boot2 release and loopback details fixed
Signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>
> build: Updated v1 index for new spring boot2 release and loopback details fixed

- index.yaml
> build: updated v1 index

- experimental/java-spring-boot2-liberty/templates/default/.vscode/launch.json
- experimental/java-spring-boot2-liberty/templates/default/.vscode/tasks.json
- experimental/quarkus/templates/default/.vscode/tasks.json
- incubator/java-microprofile/templates/default/.vscode/launch.json
- incubator/java-microprofile/templates/default/.vscode/tasks.json
- incubator/java-spring-boot2/templates/default/.vscode/launch.json
- incubator/java-spring-boot2/templates/default/.vscode/tasks.json
- incubator/java-spring-boot2/templates/kotlin/.gitignore
- incubator/java-spring-boot2/templates/kotlin/.vscode/launch.json
- incubator/java-spring-boot2/templates/kotlin/.vscode/tasks.json
- samples/sample-stack/templates/hello/.vscode/tasks.json
Signed-off-by Neeraj LAad <neeraj.laad@gmail.com>
Added missing .vscode tasks and launchers
> vscode: added vscode config files to stacks

- incubator/nodejs/image/config/app-deploy.yaml
- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
> nodejs: updated api version

- experimental/java-spring-boot2-liberty/image/config/app-deploy.yaml
- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/stack.yaml
- experimental/java-spring-boot2-liberty/templates/default/.appsody-config.yaml
- experimental/java-spring-boot2-liberty/templates/default/pom.xml
Updated apiVersion for AppsodyApplication to v1beta1
> java spring boot liberty: updated version to beta1

- incubator/java-microprofile/image/config/app-deploy.yaml
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
> microprofile: updated api version

- experimental/quarkus/image/config/app-deploy.yaml
- experimental/quarkus/image/project/pom.xml
- experimental/quarkus/stack.yaml
- experimental/quarkus/templates/default/pom.xml
> quarkus: updated api version

- incubator/nodejs-loopback/image/config/app-deploy.yaml
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
> loopback: updated api version

- incubator/swift/image/config/app-deploy.yaml
- incubator/swift/stack.yaml
> swift: updated api version

- incubator/nodejs-express/image/config/app-deploy.yaml
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
> nodejs-express: updated api version

- incubator/java-spring-boot2/image/config/app-deploy.yaml
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/kotlin/pom.xml
> spring-boot: updated api version

- experimental/nodejs-functions/image/config/app-deploy.yaml
- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/stack.yaml
> nodejsfunctions: updated api version

- index.yaml
> v1-index: updated for stack releases

- experimental/python-flask/image/Dockerfile-stack
- experimental/python-flask/image/config/app-deploy.yaml
- experimental/python-flask/stack.yaml
Updated api version and added file for Kubernetes deployment with new CLI
> python-flask: updated api version

- experimental/python-flask/stack.yaml
Updated name and description of Python Flask for website generation of stacks.
> python-flask: updated name and description for website

- incubator/nodejs-loopback/image/Dockerfile-stack
- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
> nodejs-loopback: fix https://github.com/appsody/stacks/issues/232

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/.appsody-init.bat
- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/kotlin/pom.xml
Using maven, to install maven wrapper into stack project folder at same level as stack maven binary.
> Add Maven Wrapper to Spring Boot 2 stack.

- incubator/java-microprofile/image/Dockerfile-stack
- incubator/java-microprofile/image/project/.appsody-init.bat
- incubator/java-microprofile/image/project/.appsody-init.sh
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
Using maven, to install maven wrapper into stack project folder at same level as stack maven binary.
> Add Maven Wrapper to Microprofile stack.

- ci/build.sh
- ci/package.sh
moved where we generate codewind indexes
Created code wind indexes before creating nginx image
> build:  Moved Codewind index generation

- ci/lint.sh
fixes: https://github.com/appsody/stacks/issues/275
> ci: enforce stack LICENSE

- ci/env.sh
- ci/lint.sh
- ci/list.sh
- ci/package.sh
- ci/release.sh
- ci/test.sh
> Iterate over files in directories

- ci/nginx/Dockerfile
- ci/nginx/startup.sh
> Fix yaml copy for nginx — required by kabanero 

- ci/env.sh
> preserve publish behavior of TRAVIS_TAG

- .travis.yml
- ci/build.sh
Temp fix for stacks release, moving prefetch and python back to travis.yml
> ci: fix error with stack release

- ci/prefetch.sh
> avoid dir change

- index.yaml
> index update

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
Upgraded stack to use Open Liberty v19.0.0.8 release
Fixes: https://github.com/appsody/stacks/issues/262
> java-microprofile: upgraded to use open liberty v19.0.0.8

- samples/sample-stack/image/Dockerfile-stack
- samples/sample-stack/image/config/app-deploy.yaml
- samples/sample-stack/image/project/Dockerfile
Made changes to sample-stack to provide guidance on using appsody environment variables in the ```Dockerfile-stack``` and added a sample ```app-deploy.yaml```
Fixes: https://github.com/appsody/stacks/issues/291
> sample-stack: improved guidance for stack creators

- index.yaml
> java-microprofile index.yaml: index update

- .travis.yml
> ci: remove matrix

- index.yaml
This PR adds the recently graduated python flask stack to the V1 index.
> index: adding python flask to V1 index

- incubator/java-microprofile/image/Dockerfile-stack
> ubuntu has backlevel maven. Use -B

- experimental/quarkus/image/Dockerfile-stack
- experimental/quarkus/image/project/Dockerfile
- experimental/quarkus/image/project/pom.xml
- experimental/quarkus/stack.yaml
- experimental/quarkus/templates/default/pom.xml
`--no-transfer-progress` to suppress transfer progress (bloats log files)
> Mvn squash quarkus

- incubator/java-microprofile/image/Dockerfile-stack
- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/image/project/util/RangeIncludesVersion.java
- incubator/java-microprofile/image/project/util/check_version
- incubator/java-microprofile/image/project/validate.sh
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
Moves template to using a version range for parent
Moves stack to verifying using version range.
Related to #229
> Mp version range

- ci/test.sh
Really for real make init and build quieter.
> Make init and build steps much quieter

- .travis.yml
> source the release script (preserve shell)

- incubator/java-microprofile/image/project/.appsody-init.bat
- incubator/java-microprofile/image/project/.appsody-init.sh
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
*NOTE* This follows PR #329 
Fixes warnings issued if stack is used on platform without java present.
> Mp optional mvnw (follows PR #329)

- experimental/java-spring-boot2-liberty/image/project/.appsody-init.bat
- experimental/java-spring-boot2-liberty/image/project/.appsody-init.sh
- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/stack.yaml
*NOTE* Follows PR #330
Fixes warnings issued if stack is used on platform without java present.
> Sbol optional mvnw (follows PR #330)

- experimental/vertx/image/project/pom.xml
- experimental/vertx/stack.yaml
- experimental/vertx/templates/default/pom.xml
Updated template pom.xml so child projects can allow a range of parent version
Related to #315
> vertx: allow version range

- .github/ISSUE_TEMPLATE/bug_report.md
> Include the stack version for issues

- ci/env.sh
- ci/ext/pre_env.d/10_travis
- ci/ext/pre_test.d/10_travis
- ci/nginx/Dockerfile
- ci/package.sh
- ci/test.sh
> [ci] Verbose mode with log capture

- incubator/java-spring-boot2/stack.yaml
Only change is to `stack.yaml` .. ;)
> [java-spring-boot2] Update spring stack version to 0.3.14

- index.yaml
Updated v1 index for python flask version 0.1.4 release
Related to #377
> updated v1 index

- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/image/project/server.js
- experimental/nodejs-functions/stack.yaml
> [nodejs-functions] Manage functions that are not exported as GET

- ci/build.sh
Fixes: https://github.com/appsody/stacks/issues/379
> build: remove trailing slash if present in stacks list

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/stack.yaml
Added recompile script to debug change trigger. 
Now changes made during debug will be reflected live (after recompile/restart as appropriate)
Fixes #407
> recompile on debug change

- incubator/starter/README.md
- incubator/starter/stack.yaml
Give more details on how to use this starter in the README, and provide a better name for the tile on the main web site.
Fixes #436
> [starter-stack] Improve README and name

- experimental/rust/README.md
- experimental/rust/stack.yaml
- experimental/rust/templates/simple/.vscode/launch.json
Added debugging support for vscode ide debugging
> rust: added ide debugging support

- ci/nginx/docker-compose.yml
- ci/nginx/startup.sh
- ci/package.sh
Updated the CI build scripts to correctly process the codewind json files that will be used within the generated nginx docker image.
> Correctly process the URLs in the codewind json file for the nginx image

- index.yaml
Following https://github.com/appsody/stacks/blob/master/RELEASE.md I am updating the v1 `index.yaml` file.
> Update v1 index.yaml

- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
- incubator/nodejs-loopback/templates/scaffold/package-lock.json
- incubator/nodejs-loopback/templates/scaffold/package.json
> nodejs-loopback: upgrade to latest loopback dependencies

- experimental/quarkus/README.md
- experimental/quarkus/image/project/Dockerfile
- experimental/quarkus/image/project/pom.xml
- experimental/quarkus/stack.yaml
- experimental/quarkus/templates/default/pom.xml
Upgrades the stack to use the newly released Quarkus 1.0.0. 
Fixes: https://github.com/appsody/stacks/issues/471
> quarkus: upgrade to use Quarkus 1.0.0

- incubator/nodejs-express/image/project/package-lock.json
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
- incubator/nodejs-express/templates/scaffold/package-lock.json
- incubator/nodejs-express/templates/scaffold/package.json
- incubator/nodejs-express/templates/simple/package-lock.json
Fixed audit issues with image and the 2 templates.
- Added missing package-lock.json
- Ran npm audit fix to fix any audit issues
> Node express audit fixes

- incubator/nodejs-express/image/project/server.js
> fix typo in error message

- incubator/java-spring-boot2/image/config/app-deploy.yaml
- incubator/java-spring-boot2/stack.yaml
Adds monitoring for Spring Boot 2 Java stack via Appsody Operator.
Adds required `timeoutSeconds` field for knative validation.
#391 
#313 
#441
> Add monitoring to deploy yaml

- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
- incubator/nodejs-loopback/templates/scaffold/package-lock.json
- incubator/nodejs-loopback/templates/scaffold/package.json
- index.yaml
> nodejs-loopback: update to latest version of LoopBack 4

- ci/download_cli.sh
> Update the Appsody CLI Fallback version

- incubator/kitura/stack.yaml
- incubator/kitura/templates/default/Tests/ApplicationTests/KituraStackTests.swift
Added `import FoundationNetworking` at the top of test file.
fixes #533
> Kitura stack fix

- ci/package.sh
> Updates package.sh to correctly use downloaded index files

- .gitignore
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/src/main/resources/application.properties
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/application.properties
> Move spring boot to pom.xml

- experimental/nodejs-functions/README.md
- experimental/nodejs-functions/image/Dockerfile-stack
- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/image/project/test/test.js
- experimental/nodejs-functions/stack.yaml
Updates nodejs to use version 12. Uses the new version of the nodejs express stack as specified in #555 
Fixes: #561
> nodejs-functions: update node to version 12

- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
> nodejs: update stack maintainers

- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
> nodejs-express: update stack maintainers

- .travis.yml
- ci/ci_wait.sh
- ci/env.sh
- ci/ext/pre_env.d/10_travis
- ci/ext/pre_list.d/10_travis
- ci/package.sh
- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/Dockerfile
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/image/project/util/check_version
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/src/main/resources/application.properties
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/application.properties
The stack's build instructions were modified to extract dependencies at build time. The final docker image is then constructed using those extracted dependencies.
The root vs. java user has been cleaned up in both the stack and final docker images.
The compile image is tagged with the stack image name, but is no longer the same, as it downloads and installs stack and application dependencies (in two separate layers) to help with subsequent calls to appsody build.
Fixes #527
Supersedes #543
> java-spring-boot2: publish app as layers

- .github/PULL_REQUEST_TEMPLATE.md
> Fixes PR template dead link

- incubator/java-openliberty/image/project/pom.xml
- incubator/java-openliberty/stack.yaml
> java-openliberty: Use go templating to parameterize Open Liberty version

- experimental/quarkus/image/project/pom.xml
- experimental/quarkus/stack.yaml
- experimental/quarkus/templates/default/pom.xml
> Revert "quarkus: update stack to set minimum requirements for Docker and utilise templating"

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/image/project/pom.xml
- incubator/java-openliberty/stack.yaml
- [ x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).
added a package step to maven commands coded to the appsody envvars in Dockerfile-stack
- Describe other Appsody environment variables defined by the stack …
> Add package step to maven commands associated with appsody stack variables

- incubator/java-spring-boot2/README.md
- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/.appsody-init.bat
- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/Dockerfile
- incubator/java-spring-boot2/image/project/appsody-boot2-snowdrop-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/image/project/update.sh
- incubator/java-spring-boot2/image/project/verify-property-versions.sh
- incubator/java-spring-boot2/stack.yaml
> Changes to java-spring-boot2 stack to facilitate downstream selection of snowdrop

- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
- [x ] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
- [x ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).
- [x ] Updated the stack version in `stack.yaml`
> dockerfile updates to support a pre-existing war/ear file project

- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
- Bump stack version to put src and fully qualified image in index
> nodejs: Bump stack version to put src and image in index

- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
Bump stack version to put src and image in index
> nodejs-express: Bump stack version to put src and image in index

- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
Bump stack version to put src and image in index
> java-microprofile: Bump stack version to put src and image in index

- incubator/java-spring-boot2/image/project/appsody-boot2-snowdrop-pom.xml
- incubator/java-spring-boot2/image/project/update.sh
- incubator/java-spring-boot2/stack.yaml
Bumped EPEL version for RHEL 8.
Fixed bug in snowdrop parent pom reference to parentpomid.
> bug fixes for spring boot stack EPEL and snowdrop

- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
Bump stack version to put src and image in index
> nodejs-loopback: Bump stack version to put src and image in index

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/src/main/liberty/config/configDropins/defaults/quick-start-security.xml
- incubator/java-microprofile/templates/default/src/main/liberty/config/server.xml
Remove quick start security password and default to auto-generated password.
> java-microprofile: remove quickstart security password

- incubator/java-spring-boot2/stack.yaml
Add additional stack maintainers to `java-spring-boot2` stack
> java-spring-boot2 - add additional stack maintainers to the stack

- incubator/kitura/image/project/Dockerfile
- incubator/kitura/stack.yaml
> kitura: Update to not upgrade packages in base image

- incubator/nodejs-loopback/image/project/Dockerfile
- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
Removed "apt-get upgrade"  commands so we stick with package versions provided in base stack
Updated to tar contents of /projects to resolve performance issues with buildah
Resolved some security vulnerabilities on nodejs packages
> nodejs-loopback: Update to not upgrade base image && perf changes

- incubator/node-red/image/Dockerfile-stack
- incubator/node-red/image/project/Dockerfile
- incubator/node-red/image/project/package.json
- incubator/node-red/stack.yaml
> node-red: Updates to not update base stack packages and some perf changes

- incubator/java-openliberty/README.md
- incubator/java-openliberty/image/project/pom.xml
- incubator/java-openliberty/image/project/preload-m2-pom.xml
- incubator/java-openliberty/stack.yaml
- incubator/java-openliberty/templates/default/pom.xml
Add parentpomgroup and parentpomid template variables
Add stack developer section to readme
Fixes #699
> java-openliberty: add stack template variables

- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/image/project/package.json
- incubator/nodejs-loopback/stack.yaml
- incubator/nodejs-loopback/templates/scaffold/.eslintrc.js
- incubator/nodejs-loopback/templates/scaffold/.prettierrc
- incubator/nodejs-loopback/templates/scaffold/.vscode/settings.json
- incubator/nodejs-loopback/templates/scaffold/.vscode/tasks.json
- incubator/nodejs-loopback/templates/scaffold/.yo-rc.json
- incubator/nodejs-loopback/templates/scaffold/DEVELOPING.md
- incubator/nodejs-loopback/templates/scaffold/README.md
- incubator/nodejs-loopback/templates/scaffold/index.js
- incubator/nodejs-loopback/templates/scaffold/package-lock.json
- incubator/nodejs-loopback/templates/scaffold/package.json
- incubator/nodejs-loopback/templates/scaffold/public/index.html
- incubator/nodejs-loopback/templates/scaffold/src/application.ts
- incubator/nodejs-loopback/templates/scaffold/src/controllers/ping.controller.ts
This PR upgrade `nodejs-loopback` stack to use latest version of LoopBack.
> feat: upgrade nodejs-loopback stack to the latest version of LoopBack

- ci/download_cli.sh
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
- incubator/nodejs-express/stack.yaml
Removed use of `--system` option with `update.sh` in Dockerfile-stack.
Updated relevant README info.
remove update of stack image and final image packages
https://github.ibm.com/ibmcloud/spring-at-ibm/issues/142
> retract spring boot stack image packages update

- experimental/nodejs-functions/image/project/package-lock.json
- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/templates/simple/package-lock.json
- experimental/nodejs-functions/templates/simple/package.json
- incubator/node-red/image/project/package-lock.json
- incubator/node-red/image/project/package.json
- incubator/node-red/templates/simple/package-lock.json
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/templates/scaffold/package.json
- incubator/nodejs-express/templates/simple/package-lock.json
- incubator/nodejs-express/templates/simple/package.json
- incubator/nodejs-loopback/image/project/package-lock.json
- incubator/nodejs-loopback/templates/scaffold/package-lock.json
- incubator/nodejs/image/project/package-lock.json
- incubator/nodejs/image/project/package.json
Most deps are updated by regenerating lock files, allowing the latest
semver-compatible version to be installed.
Mocha needed updating from 6.x to 7.x, but the breaking changes aren't
relevant to the simple template usage:
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#700--2020-01-05
PR diff is noisy because of package-lock.json churn, actual differences
are just:
```
diff --git a/experimental/nodejs-functions/image/project/package.json b/experimental/nodejs-functions/image/project/package.json
index eb0a141..74b456c 100644
--- a/experimental/nodejs-functions/image/project/package.json
+++ b/experimental/nodejs-functions/image/project/package.json
@@ -19,7 +19,7 @@
},
"devDependencies": {
"chai": "^4.2.0",
-    "mocha": "~6.1.0",
+    "mocha": "^7.1.1",
"request": "^2.88.0"
} …
```
> node*: update deps to address audit warnings

- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
> java-openliberty: Notify of the removal of quick-start-security.xml

- incubator/node-red/image/project/package-lock.json
- incubator/node-red/image/project/package.json
- incubator/node-red/image/project/server.js
- incubator/node-red/image/project/test/test.js
- incubator/node-red/stack.yaml
Sync with nodejs-express, see https://github.com/appsody/stacks/pull/761
> node-red: use prom-client

- incubator/nodejs-express/README.md
- incubator/nodejs-express/image/project/package-lock.json
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
- incubator/nodejs-express/image/project/test/test.js
- incubator/nodejs-express/stack.yaml
- incubator/nodejs-express/templates/scaffold/package.json
- incubator/nodejs-express/templates/simple/package.json
We recomment using prom-client rather than appmetrics-prometheus.
> nodejs-express: use prom-client

- incubator/quarkus/README.md
- incubator/quarkus/image/project/pom.xml
- incubator/quarkus/stack.yaml
- incubator/quarkus/templates/default/src/main/resources/META-INF/resources/index.html
Fix for https://github.com/appsody/stacks/issues/776
> Update Quarkus to 1.3.2.Final

- incubator/java-openliberty/README.md
Remove OL version restriction from readme
> java-openliberty: remove version restriction

- incubator/quarkus/image/config/app-deploy.yaml
- incubator/quarkus/image/project/pom.xml
- incubator/quarkus/stack.yaml
Reapply https://github.com/appsody/stacks/pull/812 to `master`.
> quarkus: add monitoring to app-deploy.yaml

- incubator/java-openliberty/README.md
Doc only, no need to re-release.
> Fix broken link

- RELEASE.md
Adds a note about necessary checks before release and removes section about the v1 index.
> release.md: add prerequisites and remove outdated sections

- experimental/rocket/stack.yaml
- Adding Enrique as maintainer
> Add Enrique as Rocket maintainer

- incubator/quarkus/README.md
- incubator/quarkus/image/project/pom.xml
- incubator/quarkus/stack.yaml
- incubator/quarkus/templates/default/pom.xml
- incubator/quarkus/templates/kafka/pom.xml
- incubator/quarkus/templates/kafka/src/main/java/org/acme/kafka/PriceConverter.java
- incubator/quarkus/templates/kafka/src/main/java/org/acme/kafka/PriceGenerator.java
As well as updating the version, I've also updated the template code to match the changes in the Quarkus quickstart that they are based on.
> Updated Quarkus stack to use Quarkus 1.6.0.Final

- incubator/java-openliberty/README.md
- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/image/mvn-stack-settings.xml
- incubator/java-openliberty/stack.yaml
- [x ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).
- [x ] Updated the stack version in `stack.yaml`
Fixes #857
> Issue 857: add maven settings.xml and update liberty version

- README.md
n/a - not modifying an existing stack
n/a - not contributing a new stack
> Update README to reflect end of Appsody development

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
> up maven image level
