appsody/stacks

- index.yaml
The CLI needs a consistent URL to reference an ever changing index.yaml file. Github releases won't work because the version tag changes in the URL. So we are placing it in the stacks repo and using the github RAW link to access it.
> Adding index.yaml to the stacks repo

- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
The use of `vhost` with `*` works on localhost, but fails when running under Knative serving with a mapped domain. As it turns out, the use of vhost isn't required - we can use use `app.use('.
/', userApp)` to register the users application on the root url.
I'm also moved this above the health/liveness/readiness endpoints in order to allow users to override those with their own.
> [nodejs-express] Remove use of vhost

- incubator/java-microprofile/image/Dockerfile-stack
This avoids Appsody container creating files on the host system.
> java-microprofile: update to specifically mount src and pom.xml

- incubator/nodejs-express/README.md
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
- incubator/nodejs-express/stack.yaml
- incubator/nodejs/README.md
- incubator/nodejs/image/Dockerfile-stack
- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
The Eclipse Codewind project uses the `appmetrics-dash` NPM module to provide development time application monitoring and performance testing data.
This updates the nodejs and nodejs-express stacks to add appmetrics-dash as a devDependency.
For the nodejs stack, this is done using `attach()`, which means it will only be added if the app provides some form of HTTP server. This is deliberate so that adding the dashboard doesn't prevent applications that are batch jobs etc from exiting.
> [nodejs] Add appmetrics-dash as a dev dependency

- index.yaml
- Updating index for java-spring-boot2 v0.3.1 (adds index page on default route)
> Updating index for java-spring-boot2 v0.3.1

- incubator/java-microprofile/image/Dockerfile-stack
Fixes #
Related to https://github.com/appsody/controller/issues/7
I propose using `mvn package` rather than `mvn compile` in the java-microprofile stack ON_CHANGE command. 
The reason is that `package` allows liberty to pick up config changes to server.xml such as creating new endpoints or features. In an obscure case (which we hit testing https://github.com/appsody/controller/issues/7 ) if the liberty server is started with a compile error in one of the endpoints, fixing the compile error and running `mvn compile` does not enable the endpoint but `mvn package` does.
See also https://openliberty.io/guides/getting-started.html#updating-the-server-configuration-without-restarting-the-server
The downside of this is a longer ON_CHANGE command. On my local machine it takes roughly 3 secs to …
> Use mvn package instead of compile on change

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/Dockerfile
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/stack.properties
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/kotlin/.appsody-config.yaml
- incubator/java-spring-boot2/templates/kotlin/.gitignore
- incubator/java-spring-boot2/templates/kotlin/pom.xml
- incubator/java-spring-boot2/templates/kotlin/src/main/java/application/Main.java
- incubator/java-spring-boot2/templates/kotlin/src/main/kotlin/application/Hello.kt
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/application.properties
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/public/index.html
- incubator/java-spring-boot2/templates/kotlin/src/test/java/application/MainTests.java
Adds Kotlin compiler to the base Spring Boot 2 stack. 
Adds Kotlin Template to the Spring Boot 2 stack. (Pending resolution of Issue https://github.com/appsody/appsody/issues/38 )
Note there are some gymnastics here to enable Kotlin version to be defined outside the Dockerfiles, ideally the version should also be used to generate? the parent pom, but for now the cleanest route is to just have the version defined in two places. This places an added burden on the Stack author to ensure the version remains in sync in both places, but since a human is involved, maintains a lower risk of accidentally creating multiple parent poms with the same maven coordinates (group/artifact/version) but with different content (this would be bad).
Related to PR#101, but adds Kotlin to the base boot stack, …
> Add Kotlin Template to Spring Boot Stack

- ci/list.sh
The problem arose because no stacks are detected when the `stacks` folder was named anything else. stacks is currently a hardcoded value in the `list.sh` script. implementing a change that subtracts the base directory from the pwd for the stack.
The full set of stacks in the incubator, stable and experimental directories should now be found.
ie: from my working system.
Fixes: https://github.com/appsody/stacks/issues/153
> stacks-build: fix hardcoded directory for local build

- experimental/nodejs-functions/stack.yaml
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
Updated version of appmetrics-dash for nodejs and nodejs-express stacks. Reduces amount of deprecated declarations when building stacks from build.sh script.
> nodejs: bumped version of appmetrics-dash

- incubator/nodejs-express/image/project/package.json
Node modules don't get inherited from the nodejs image. Instead the nodejs-express replaces the node_modules folder with its dependancies
> nodejs-express: adding appmetrics-dash as a dependancy

- incubator/nodejs-express/image/project/package.json
appmetrics-dash depends on 3.0.0 version of appmetrics-prometheus
> nodejs-express: appmetrics-dash depends on 3.0.0 on prometheus

- incubator/swift/README.md
- incubator/swift/image/project/Dockerfile
- incubator/swift/stack.yaml
This adds support for multi-stage docker builds for the final "production" build that's invoked using `appsody build`.
> swift: add support for swift-slim production images

- experimental/nodejs-functions/templates/simple/.vscode/launch.json
- experimental/nodejs-functions/templates/simple/.vscode/tasks.json
- incubator/nodejs-express/templates/simple/.vscode/launch.json
- incubator/nodejs-express/templates/simple/.vscode/tasks.json
- incubator/nodejs-express/templates/skaffold/.vscode/launch.json
- incubator/nodejs-express/templates/skaffold/.vscode/tasks.json
- incubator/nodejs/templates/simple/.vscode/launch.json
- incubator/nodejs/templates/simple/.vscode/tasks.json
- incubator/swift/templates/simple/.vscode/tasks.json
Fixed errors for the `launch.json` and `tasks.json` files when importing an appsody project into Eclipse. Removed comments in both files and the trailing ',' in` tasks.json`
Fixes: #126
> stacks: fixed errors when importing projects to Eclipse

- ci/build.sh
- ci/env.sh
Added environment variable `CODEWIND_JSON`. The create_codewind_index.sh script only runs if `CODEWIND_JSON` is set to true. 
Fixes: #179
> build: limit create_codewind_index.sh

- incubator/swift/image/Dockerfile-stack
- incubator/swift/image/project/Dockerfile
- incubator/swift/stack.yaml
This adds `apt-get install -y zlib1g-dev` to `Dockerfile-stack` for development and to the production `Dockerfile` for use by Vapor based apps.
> [Swift] Add apt-get zlib1g-dev for use by Vapor apps

- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/stack.yaml
- experimental/java-spring-boot2-liberty/templates/default/pom.xml
Bumped version of java-spring-boot2-liberty to fix pinned specific patch version in the templates
> java-spring-boot on liberty: bumped version

- .gitignore
- .travis.yml
- ci/build.sh
- ci/env.sh
- ci/lint.sh
- ci/list.sh
- ci/nginx/Dockerfile
- ci/nginx/docker-compose.yml
- ci/nginx/nginx.conf
- ci/nginx/startup.sh
- ci/package.sh
- ci/prefetch.sh
- ci/release.sh
- ci/test.sh
N/A
This updates release packaging to also create a nginx docker image containing the index.yaml files and associated tar.gz. This docker image can be used in environments where git release links won't work (e.g. protected by SAML), and other binary repositories aren't desired.
The `ci/nginx` directory, contains a Dockerfile and nginx.conf file to create an nginx server image (`appsody-index`) that can serve static index and template resources. A `docker-compose.yml` file is also present to make the contents of this image easier to test and verify. Use a `docker-compose.override.yml` file to replace the `{{EXTERNAL_URL}}` value if necessary for local testing. The nginx container can be added to your local appsody repository.
$ cd ci/nginx
$ docker-compose up verify        # dump index …
> Nginx image for index + tar.gz; pass additional parameters to docker build

- ci/build.sh
- ci/nginx/Dockerfile
- ci/nginx/docker-compose.yml
- ci/package.sh
- ci/prefetch.sh
1. Move prefetch template archives into the build directory so they are not included in the GitHub release.
2. Clean up prefetch template archives when a new one is built
3. Include prefetched template archives (from new location) in the index image.
> move prefetched binaries to the build directory

- experimental/java-spring-boot2-liberty/image/Dockerfile-stack
- experimental/java-spring-boot2-liberty/image/project/.appsody-init.bat
- experimental/java-spring-boot2-liberty/image/project/.appsody-init.sh
- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/stack.yaml
- experimental/java-spring-boot2-liberty/templates/default/pom.xml
Adds Maven Wrapper to Spring Boot2 on Open Liberty Stack
> Add Maven Wrapper to Spring Boot2 on Open Liberty stack.

- ci/nginx/Dockerfile
- ci/nginx/docker-compose.yml
- ci/nginx/nginx-ssl.conf
- ci/nginx/startup.sh
Requires PR #219 
If `EXTERNAL_URL` contains `https`, use the SSL configuration file instead. 
The docker-compose file maps ports to avoid conflict with application containers when testing locally:
*  8080 is mapped to 8008 
*  8443 is mapped to 8003
Requires PR #219 
Related to issue kabanero-io/kabanero-collection#60
Includes changes from PR kabanero-io/collections#35
> Add support for SSL to nginx image

- .gitignore
- ci/env.sh
- ci/nginx/docker-compose.yml
- ci/package.sh
- ci/release.sh
Replace DOCKER* environment variables with IMAGE_REGISTRY*
Define functions for docker operations, to allow buildah replacement
Allow registry push to be disabled
> Allow buildah in place of docker CLI

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/.appsody-init.bat
- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/kotlin/pom.xml
Make maven quieter for docker/build logs
Fix path in init scripts
> java-spring-boot2: init script path; hush progress

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/src/main/resources/application.properties
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/application.properties
Spring dev tools used to manage restart when .class or related resources were updated. 
There appears to be a timing window, during a maven build, when Spring may choose to restart the app, and bring the app up based on partially compiled changes, and then also not notice that further compiles occured during the app start, leaving the app running in an inconsistent state.
Moving the restart to be trigger based will avoid this window, Spring dev tools is configured here to restart only when a trigger file is updated, and the parent pom build is updated to touch that file after the compile step has completed. 
Non-compiling-editors: (vim/notepad/ultraedit etc)
Edits are made to the source, detected by the appsody watcher, which in turn triggers the mvn compile, that after completion touches …
> Restart on trigger

- incubator/java-microprofile/image/Dockerfile-stack
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
`--no-transfer-progress` to suppress transfer progress (bloats log files)
> suppress maven progress output for microprofile

- experimental/java-spring-boot2-liberty/image/Dockerfile-stack
- experimental/java-spring-boot2-liberty/image/project/Dockerfile
- experimental/java-spring-boot2-liberty/image/project/pom.xml
- experimental/java-spring-boot2-liberty/stack.yaml
- experimental/java-spring-boot2-liberty/templates/default/pom.xml
`--no-transfer-progress` to suppress transfer progress (bloats log files)
> suppress maven progress output for Spring+Liberty

- experimental/vertx/image/Dockerfile-stack
- experimental/vertx/image/project/Dockerfile
- experimental/vertx/image/project/pom.xml
- experimental/vertx/stack.yaml
- experimental/vertx/templates/default/pom.xml
` --no-transfer-progress` to suppress transfer progress (bloats log files)
> suppress maven progress output for vertx

- .gitignore
- .travis.yml
- ci/env.sh
- ci/ext/pre_env.d/10_travis
- ci/ext/pre_list.d/10_travis
- ci/ext/pre_test.d/10_travis
- ci/test.sh
Provide basic contents in test.sh to ensure that stack templates
can be run, and that projects can be extracted and built using
specified stack(s)
Travis builds:
- Install appsody CLI if missing.
- Use a subset of known stacks when nothing else is specified
- Wrap long-running commands to prevent exit from no console output
- N/A Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).
> Basic test functionality for CI builds

- ci/build.sh
- ci/env.sh
- ci/ext/pre_list.d/10_travis
- ci/list.sh
- ci/package.sh
- ci/prefetch.sh
- ci/test.sh
- Better fallback if travis commit range is fubar using prefetch data
- Fix pull policy for tests
- N/A Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).
> [ci] Fallback travis stack list; fix tests

- ci/create_codewind_index.py
- ci/env.sh
- ci/package.sh
The create_codewind_index python script is hard coded to specify "Appsody" at the start of the displayName of all the stacks that are included in the index.json file. There is a requirement to allow this to be configurable. This PR allows an environment variable to be set DISPLAY_NAME_PREFIX (eg export DISPLAY_NAME_PREFIX="Appsody") whose value will be used at the front of all the displayName strings in the index.json.
> Use a variable as a prefix for the codewind index stack display names

- incubator/nodejs-express/image/config/app-deploy.yaml
- incubator/nodejs-express/image/project/Dockerfile
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
Updated the production image to set the NODE_PATH environment variable to point to the node_modules folder in the user's app. Added timeoutSeconds for Readiness probe in `app-deploy.yaml`
Fixes #321 
Related to #313
> nodejs-express: added environment variable to production image

- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/stack.yaml
Fixes path to parent pom in init.sh
Signed-off-by Neeraj Laad <neeraj.laad@gmail.com
> spring-boot: Fix path to pom.xml

- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/stack.yaml
- incubator/java-spring-boot2/templates/default/src/main/resources/application.properties
Trigger behavior altered.. 
- watcher trigger restricted to a selection of filetypes (to be redone after resolution of APPSODY_WATCH_REGEX issue)
- spring trigger moved to target folder
- spring dev tools made optional based on launch script set env var rather than appsody run
> alter trigger behavior

- README.md
- TECHNICAL_REQUIREMENTS.md
- experimental/nodejs-functions/README.md
- incubator/nodejs/README.md
Fixed a couple of typos I found across some of the markdown files
> nodejs-functions: fix typos in readme

- incubator/python-flask/image/Dockerfile-stack
There are no directories within the user application directory, so no need to define any watch ignore directories.
Fixes #350
> python-flask: unset watch ignore directory

- ci/env.sh
- ci/package.sh
- incubator/java-spring-boot2/image/Dockerfile-stack
- incubator/java-spring-boot2/image/project/.dockerignore
- incubator/java-spring-boot2/image/project/Dockerfile
- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/templates/default/.gitignore
- incubator/java-spring-boot2/templates/default/pom.xml
- incubator/java-spring-boot2/templates/kotlin/.gitignore
- incubator/java-spring-boot2/templates/kotlin/pom.xml
- incubator/java-spring-boot2/templates/kotlin/src/main/resources/application.properties
Arguments passed in by package.sh are used to version the stack image
The compile stage of the Dockerfile used to build the final image is based on the stack image
Fix bugs in Spring Boot stack:
- Exposed ports
- exec used so signals go to java process
Related to #181 and #324 
---
After these changes are applied, the stack image contains (already defined by package.sh):  
```            "Labels": {
"appsody.stack": "appsody/java-spring-boot2:0.3.13",
"org.opencontainers.image.created": "2019-09-23T13:23:11-0400",
"org.opencontainers.image.revision": "9eb6942fc3ee2afe2f208970dd2ab3e5de20f70c",
"org.opencontainers.image.version": "0.3.13"
}
```
The final docker image contains the stack version as well: 
```
"Labels": {
"appsody.stack": "appsody/java-spring-boot2:0.3.13", …
```
> [java-spring-boot2] Use git and version data in stack image

- incubator/python-flask/README.md
- incubator/python-flask/image/Dockerfile-stack
- incubator/python-flask/image/project/Dockerfile
- incubator/python-flask/image/project/Pipfile
- incubator/python-flask/stack.yaml
The current flask version was rather old, this updates it 1.1.1.
There are also a few cleanups that have been done, e.g.:
- Ensure flask is in debug mode (as well as the already enabled ptvsd) in APPSODY_DEBUG
- Use $APPSODY_XXX wherever possible in Dockefile-stack
- Better document debug mode in README.
- Remove unused gunicorn
- Use standard /project directory in Dockerfile
Fixes #376
> [python-flask] Move flask to 1.1.1, plus other minor cleanups

- experimental/vertx/image/config/app-deploy.yaml
- experimental/vertx/image/project/pom.xml
- experimental/vertx/stack.yaml
Related to: https://github.com/appsody/stacks/issues/313#event-2683805266
> vertx: define timeout seconds for readiness probe

- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
- incubator/java-microprofile/templates/default/pom.xml
- incubator/java-microprofile/templates/default/src/test/java/it/dev/appsody/starter/HealthEndpointTest.java
This PR reverts appsody/stacks#397 as we noticed 2 issues:
- looseApplicaiton check was in place but the pom removed the setting.
- user's changes are not reflected properly in the running container
Updates the stack to a new version to allow a new release.
Signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>
> java-microprofile Revert "#364 improve pom.xml by adopting agreed best practices"

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/Dockerfile-stack
- incubator/java-microprofile/image/project/install-dev-deps.sh
- incubator/java-microprofile/image/project/pom-dev.xml
- incubator/java-microprofile/image/project/server-dev.xml
- incubator/java-microprofile/stack.yaml
This adds Javametrics-dash as a dev only dependency as part of the stack. This both provides developers with a build-in performance view, and enables the Eclipse Codewind IDE project to do application monitoring and performance testing the of the application during development.
The approach to providing the Javametrics dashboard during development only is as follows:
* Provide a pom-dev.xml file that installs the dependencies as installs them into the server which is only run in Dockerfile-stack, and not in the production Dockerfile.
* Provide a server-dev.xml that adds the necessary features that is only copied into the config dropins the Dockerfile-stack, and not in the production Dockerfile.
This pattern can be extended if there's further capabilities that we want to provide only …
> [java-microprofile] Add javametrics as a dev only dependency

- experimental/rust/image/project/Dockerfile
- experimental/rust/stack.yaml
Before we were running `cargo run` to get the executable path, but this is the wrong behavior for `appsody build`. I have changed this so we run `cargo build --release` and recursively look for the built binary instead
> rust: improve method for getting name of binary for build

- ci/ext/pre_test.d/10_travis
Update fallback cli version to 0.4.7
> ci: Update fallback cli version to 0.4.7

- incubator/kitura/README.md
- incubator/kitura/image/.dockerignore
- incubator/kitura/image/Dockerfile-stack
- incubator/kitura/image/LICENSE
- incubator/kitura/image/config/app-deploy.yaml
- incubator/kitura/image/project/.appsody-init.sh
- incubator/kitura/image/project/.dockerignore
- incubator/kitura/image/project/Dockerfile
- incubator/kitura/image/project/deps/AppsodyKitura/Package.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Sources/AppsodyKitura/AppsodyKitura.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Sources/AppsodyKitura/Logging.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Sources/AppsodyKitura/Metrics.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Sources/AppsodyKitura/Routes/HealthRoutes.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Tests/AppsodyKituraTests/RouteTests.swift
- incubator/kitura/image/project/deps/AppsodyKitura/Tests/LinuxMain.swift
- incubator/kitura/stack.yaml
- incubator/kitura/templates/default/.gitignore
- incubator/kitura/templates/default/Package.swift
- incubator/kitura/templates/default/Sources/Application/Application.swift
- incubator/kitura/templates/default/Sources/server/main.swift
- incubator/kitura/templates/default/Tests/ApplicationTests/KituraStackTests.swift
- incubator/kitura/templates/default/Tests/ApplicationTests/RouteTests.swift
- incubator/kitura/templates/default/Tests/LinuxMain.swift
A new stack, based on top of the `appsody/swift` stack, suitable for developing a Kitura application.  Metrics and health endpoints are baked in to the stack.
The template's application's dependencies are provided by a Swift package called `AppsodyKitura`. This package in turn depends on `Kitura`, `SwiftMetrics` and the other Swift packages required to build a Kitura app.
AppsodyKitura is provided as a local Swift package in the base image.  In order to allow local builds and functioning code completion in IDEs (eg. Xcode), the dependencies are copied into the user's local directory under a `.appsody` subdirectory.  This code is replaced during `appsody build` with a pristine copy of the dependencies.
As there is nothing technically …
> swift: Initial version of Kitura stack

- incubator/kitura/README.md
- incubator/kitura/image/Dockerfile-stack
- incubator/kitura/image/project/Dockerfile
- incubator/kitura/image/project/deps/AppsodyKitura/Package.swift
- incubator/kitura/stack.yaml
- incubator/kitura/templates/default/.vscode/launch.json
- incubator/kitura/templates/default/.vscode/tasks.json
- incubator/kitura/templates/default/Package.swift
Updates the `incubator/kitura` stack to use Swift 5.1, and updates the Kitura version to 2.9.
Also adds debugging configuration for VSCode as well as a copy of the VSCode tasks defined in the swift stack.
Note: depends on updated Swift stack (#444)
> Update kitura stack to Kitura 2.9 and Swift 5.1

- experimental/vertx/image/project/pom.xml
- experimental/vertx/stack.yaml
Updated stack.yaml to use appropriate SPDX License ID vs using the full license name.
Current `stack.yaml` was using a long name for license field and that includes characters that are not allowed as image or k8s label value. Updated the file to use the equivalent license ID.
> Vertx: Updated stack.yaml to use SPDX license id instead of long name

- incubator/swift/image/Dockerfile-stack
- incubator/swift/image/project/Dockerfile
- incubator/swift/stack.yaml
Fix CLI warning when using the `swift` stack by defining `APPSODY_PROJECT_DIR`:
```
[Warning] The stack image does not contain APPSODY_PROJECT_DIR. Using /project
```
Swift 5.1 changes the compiler output so it no longer includes the relative path to the build executable. Update the deploy `Dockerfile` to add the correct path to `run.sh` so that the built Docker image can be successfully deployed to k8s.
> swift: fix deploy

- incubator/swift/image/Dockerfile-stack
- incubator/swift/stack.yaml
The base `swift:5.1` Docker image defines two labels: `Description`
and `maintainer`. These were being propagated through to the
`appsody/swift` images, which was misleading as the wrong maintainer was
listed in our image.
Override these labels in the Swift stack's `Dockerfile-stack` so that
the correct information appears in `docker describe` output.
> swift: override Docker labels from base image

- experimental/quarkus/README.md
Correction to image tag - appsody-quarkus:latest; not default:latest
For "appsody build" command on "quarkus" stack, the image is tagged as "appsody-quarkus:latest"
...
...
[Docker] Successfully tagged appsody-quarkus:latest
...
...
Running "docker run...." command for "default:latest" yields 
`"Unable` to find image 'default:latest' locally
docker: Error response from daemon: pull access denied for default, repository does not exist or may require 'docker login': denied: requested access to the resource is denied." `
Hence, creating PR to update GitHub documentation from "default:latest" to appsody-quarkus:latest
- …
> Correction to image tag - appsody-quarkus:latest

- incubator/swift/README.md
- incubator/swift/stack.yaml
Swift 5.1.2 is now released, and includes important fixes for LLDB debugging which improve the behaviour of `appsody debug`.
Bump the stack version so that the Docker image will be rebuilt, picking up Swift 5.1.2.
> swift: bump stack version for Swift 5.1.2

- incubator/kitura/stack.yaml
Now that a version of the `swift` Appsody image has been released based on Swift 5.1.2, we need to re-spin the Kitura image too.
> kitura: update to respin Docker image

- incubator/python-flask/image/Dockerfile-stack
- incubator/python-flask/image/project/Dockerfile
- incubator/python-flask/stack.yaml
Expose the liveness port in the application docker file (it was only being exposed in the stack docker file). Without this,  k8s  would consider the pod to be dead.
Fixes #461
> [python-flask] Ensure liveness port is exposed

- incubator/java-spring-boot2/image/config/app-deploy.yaml
- incubator/java-spring-boot2/stack.yaml
Add a timeoutSeconds element to the readinessProbe in the app-deploy.yaml file to resolve an issue with KNative Service creation.
Related to #313
> springboot - Add readinessProbe.timeoutSeconds to app-deploy.yaml

- incubator/java-microprofile/image/config/app-deploy.yaml
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
Add a timeoutSeconds element to the readinessProbe in the app-deploy.yaml file to resolve an issue with KNative Service creation.
Related to https://github.com/appsody/stacks/issues/313
> microprofile - Add timeoutSeconds to readinessProbe in app-deploy.yaml

- incubator/nodejs-express/image/Dockerfile-stack
nodejs-express: Set APPSODY_PROJECT_DIR (to the default)
Avoid the warning from appsody init:
[Warning] The stack image does not contain APPSODY_PROJECT_DIR.  Using /project
nodejs-express: Use APPSODY_PREP instead of APPSODY_INSTALL
As recommended:
% appsody stack lint
LINTING nodejs-express
Linting Dockerfile-stack:
/home/sam/w/ibm-cloud/appsody-stacks/incubator/nodejs-express/image/Dockerfile-stack
[Warning] APPSODY_INSTALL should be deprecated and APPSODY_PREP should be used instead
> nodejs-express: fix appsody init and lint warnings

- incubator/nodejs-express/README.md
- incubator/nodejs-express/image/project/package-lock.json
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
Most important feature:
> Starting with this version, Express supports Node.js 10.x and 12.x.
Changelog: https://expressjs.com/en/changelog/4x.html
> nodejs-express: update express to 4.17

- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
Previously, `appsody build` would hang when attempting to download the `open-liberty-runtime` zip. By running the mvn command associated with this in batch, the download completes successfully.
cc @scottkurz - Should we be running all mvn commands as batch?
Fixes: https://github.com/appsody/stacks/issues/479#issuecomment-558307459
> java-microprofile: run mvn command in batch to prevent hanging build

- .gitignore
- incubator/java-spring-boot2/image/project/.appsody-init.bat
- incubator/java-spring-boot2/image/project/.appsody-init.sh
- incubator/java-spring-boot2/image/project/java-spring-boot2-build.sh
- incubator/java-spring-boot2/stack.yaml
* The stack will copy mvnw (and supporting files) to the new project at init time, which means that mvnw does not need to be installed by every individual template.
* The launch script will use exec when launching maven, to ensure that all signals go directly to the maven process (as they would when running directly on the command line).
> java-spring-boot2: Use exec and mvnw

- experimental/nodejs-functions/image/Dockerfile-stack
- experimental/nodejs-functions/image/project/package.json
- experimental/nodejs-functions/stack.yaml
- Fixes the Linter problems for nodejs-functions by adding inherited commands from nodejs-express into the stack
- Replaces `APPSODY_INSTALL` with `APPSODY_PREP` which was previously causing issues with inheritance from `nodejs-express`
- Adds a test file and directory to the template
Fixes: https://github.com/appsody/stacks/issues/534
> nodejs-functions: fix linter and appsody test errors

- ci/download_cli.sh
- ci/env.sh
- ci/package.sh
Added support for the --image-registry argument on the appsody stack package and validate commands
Fixes https://github.com/appsody/stacks/issues/563
> Add support for the --image-registry argument on appsody stack cmds

- ci/ext/pre_list.d/10_travis
- Currently the travis build time for non stack specific changes builds 4 different stacks as default. This can cause the travis build to take upwards of 45 minutes. This PR alters the list in hopes to improve this.
> Altered default travis stacks list to improve build time

- experimental/quarkus/image/project/.appsody-init.bat
- experimental/quarkus/stack.yaml
- [X ] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).
- [ X] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
- [X ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).
- [X ] Updated the stack version in `stack.yaml`
Partial fix to #538 (fixes for this stack).
> Fix appsody init on Windows for quarkus stack.

- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/image/project/preload-m2-pom.xml
- incubator/java-openliberty/image/project/validate.sh
- incubator/java-openliberty/stack.yaml
This intends to do a few things to improve the overall performance of `appsody build` for the java-openliberty stack.
1.  Introduces a POM just for the purpose of priming the build's .m2/repository with MicroProfile and maven plugin dependencies. 
2.  Performs a Liberty install and server create before any application code is copied into the build
3.  Tweaks the validate.sh script to use the regular ~/.m2/repository during appsody build rather than the /mvn/repository it continues to use in run/debug/test.
* Improve performance of "appsody build" by layering a pre-populated mvn repository and an already-installed Open Liberty.
> java-openliberty:  Cache maven dependencies for `appsody build`

- ci/download_cli.sh
> Use environment variable for APPSODY_CLI_DOWNLOAD_URL if set

- incubator/java-openliberty/README.md
- incubator/java-openliberty/stack.yaml
- incubator/java-openliberty/templates/default/pom.xml
- incubator/java-openliberty/templates/default/src/test/java/it/dev/appsody/starter/EndpointTest.java
- incubator/java-openliberty/templates/default/src/test/java/it/dev/appsody/starter/HealthEndpointTest.java
- [ x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).
- [x ] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stacks-overview.md#stack-structure).
Updated java-openliberty stack default template to use Junit 5 and added a basic endpoint test.
Fixes #595 
Switch the default template application to use JUnit 5.
> java-openliberty: use Junit 5 in default template

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/image/project/pom.xml
- incubator/java-openliberty/image/project/validate.sh
- incubator/java-openliberty/stack.yaml
- [ x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).
* Update the Liberty Maven Plugin to version 3.2
* Add requirement in enforcer plugin to use LMP version 3.2
Fixes #608 
* Updates the Liberty Maven plugin version to 3.2
> java-openliberty: update LMP version to 3.2

- incubator/swift/stack.yaml
> swift: Bump stack version to put src and image in index

- incubator/kitura/stack.yaml
> kitura: Bump stack version to put src and image in index

- incubator/node-red/image/project/package.json
- incubator/node-red/stack.yaml
cc @knolleary - Please take a look :)
> node-red: Bump stack version to put src and image in index

- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/image/project/pom.xml
- incubator/java-microprofile/stack.yaml
Update the java-microprofile stack to use Open Liberty version 19.0.0.12
Make the stack image version of OL consistent with the build image version of OL
Fixes #644
> java-microprofile: upgrade OL version

- incubator/python-flask/image/Dockerfile-stack
- incubator/python-flask/stack.yaml
cc @henrynash - Please take a look :)
> python-flask: Bump stack version to put src and image in index

- incubator/starter/stack.yaml
> starter: Bump stack version to put src and image in index

- .gitignore
In the travis step, the `download_cli.sh` creates a `cli/` folder. When the `appsody stack package` command runs, it retrieves git information that is added as labels to the stack image pushed to DockerHub. Since a new folder has been created, the label containing the git commit highlights this untrack change by adding a prefix `-modified` to the commit sha. 
To solve this, we add the `cli/` folder to the `.gitignore`.
> Add cli folder to gitignore

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/stack.yaml
The quickStartSecurity password was wrongly baked into the stack image.    Removing so it is generated on each `appsody run/debug/test`.
(Note: this is the same as:  https://github.com/kabanero-io/collections/pull/272).
> Remove liberty:create from stack image to avoid hardening pwd

- ci/git_setup.sh
During the `git_setup.sh`, we used to modify the `$TRAVIS_BRANCH` which was later on being used to determine if a stack should be released or not.
This PR changes the `git_setup.sh` to not modify `$TRAVIS_BRANCH`, but instead just use `$RELEASE_BRANCH`
> Fixing Release script on Travis

- experimental/rust/stack.yaml
There was a bug causing a few stacks released in the past couple of days to not be pushed to Docker hub. This PR bumps the version so that we can release the stacks properly.
> rust: Update version to rerelease stack

- incubator/kitura/image/Dockerfile-stack
- incubator/kitura/stack.yaml
Copies `/project/deps` folder to `/project/user-app/.appsody` in the container if it doesn't exist in the user's project (because the init script failed)
Fixes #610
> kitura: ensure .appsody folder exists in container

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/stack.yaml
* Switch to java_user in stack build, before doing maven installs.
Fixes #678
> Perform mvn install as java_user

- incubator/nodejs/image/project/Dockerfile
- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
We are seeing significant performance issues with all Node.js based stacks to build the final application image when using buildah (instead of docker).
This is because of a known issue with buildah 1.9.0. We can not upgrade the buildah version because of other issues. 
This is a temporary fix to optimize the number of files we copy during the build process.
> nodejs - Optimize copy for buildah

- incubator/nodejs-express/image/project/Dockerfile
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
Because we don't change directory back into /project, there was an error when running the built image as no package.json could be found. This (hopefully) fixes that.
cc @sam-github 
Fixes: https://github.com/appsody/stacks/issues/696
> nodejs-express: change back into /project dir at the end of build

- incubator/java-spring-boot2/image/project/appsody-boot2-pom.xml
- incubator/java-spring-boot2/image/project/appsody-boot2-snowdrop-pom.xml
- incubator/java-spring-boot2/stack.yaml
Update stack parent pom for newer spring boot fix level.
review spring boot stack's spring boot version for 03/2020
https://github.ibm.com/ibmcloud/spring-at-ibm/issues/141
> bump spring boot stack spring version to 2.1.12

- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
> java-openliberty:keystore.xml perms not set correctly

- incubator/nodejs/image/Dockerfile-stack
- incubator/nodejs/image/project/Dockerfile
- incubator/nodejs/image/project/package.json
- incubator/nodejs/stack.yaml
> nodejs: Stack use only package versions defined in base image

- incubator/nodejs-express/image/Dockerfile-stack
- incubator/nodejs-express/image/project/Dockerfile
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/stack.yaml
> nodejs-express: Stack to only use base image packages 

- ci/env.sh
Increased the ci timeout from 40 mins to 60 mins as some stacks can take longer to validate.
> Change ci-timeout from 40 mins to 60 mins

- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
- incubator/nodejs-express/stack.yaml
Previously, `appmetrics=prometheus` was being loaded too late in the production build and therefore some metrics were lost. After changes (we can see more than just os metrics again):
```
os_cpu_used_ratio 0.0621999
process_cpu_used_ratio 0.000555356
os_resident_memory_bytes 1989357568
process_resident_memory_bytes 65122304
process_virtual_memory_bytes 1277386752
http_requests_total{code="200", handler="/metrics", method="get"} 6
http_request_duration_microseconds{handler="/metrics",quantile="0.5"} 0.5419
http_request_duration_microseconds{handler="/metrics",quantile="0.9"} 6.9138
http_request_duration_microseconds{handler="/metrics",quantile="0.99"} 6.9138
http_request_duration_microseconds_sum{handler="/metrics"} 9.5546
http_request_duration_microseconds_count{handler="/metrics"} 6
``` …
> nodejs-express: require appmetrics prometheus earlier in server.js

- .travis.yml
- ci/download_cli.sh
Travis is hitting a limit of https requests to Github to download the CLI. Adding read only token to increase this limit.
> Fix download cli

- incubator/swift/README.md
Removed reference to `--no-template` in the README, as this flag has been deprecated and should now be `none`.
> Update swift stack README.md to remove deprecated flag reference

- incubator/swift/README.md
- incubator/swift/image/project/Dockerfile
- incubator/swift/stack.yaml
Avoids swift `#file` paths being invalid when used to look up relative paths to resources.
This was resulting in Kitura's `FileResourceServer` logging errors (due to a design flaw) when the initial landing page is viewed after embedding an existing Kitura project into a project based on the `swift` stack.
> Swift: Preserve build path between build and run stages

- incubator/java-openliberty/image/project/pom.xml
- incubator/java-openliberty/stack.yaml
- [x ] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
Add `serverStartTimeout` property to parent pom to provide a larger timeout for non-template projects. 
Fixes #694
> java-openliberty: add serverStartTimeout config to stack pom

- incubator/python-flask/stack.yaml
Due to a bug with the indexes fixed by: https://github.com/appsody/stacks/pull/727 a few stacks lost the `src` and `image` information in the index. Rebumping the version so that this info can be put back in.
cc @henrynash PTAL :)
> python flask: bump stack version to put src and image in the index

- incubator/starter/stack.yaml
Due to a bug with the indexes fixed by: https://github.com/appsody/stacks/pull/727 a few stacks lost the `src` and `image` information in the index. Rebumping the version so that this info can be put back in.
cc @henrynash PTAL :)
> starter: bump stack version to put src and image in the index

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/stack.yaml
- incubator/java-openliberty/image/project/Dockerfile
> 704 document quick start removal

- incubator/java-microprofile/README.md
- incubator/java-microprofile/image/project/Dockerfile
- incubator/java-microprofile/stack.yaml
Deprecate the Java Microprofile Stack
- Update stack description to show deprecation
- Mark stack as deprecated in stack.yaml
- Indicate deprecation in Readme
Fixes #751
> java-microprofile: deprecate stack

- ci/ext/pre_list.d/10_travis
- ci/package.sh
Currently, on a stack release the stack will be being built is determined from the TRAVIS_TAG.
When using the TRAVIS_TAG, If a stack is moved or deleted  that stack is not added to the list to be built. This causes issues as a deleted / removed stack will not be removed from the index file.
This PR changes the way   the stacks to be built are checked. When a release. build is being performed the commit that is associated with the TRAVIS_TAG is checked to see which stacks in the commit match the stack name in the TRAVIS_TAG. If this check doesn't find any matching stacks then the stack named in the TRAVIS_TAG is added to the built list for each repo that is configured. 
This latter check will aways add the stack for each repo, but this …
> Check which stacks are updated or deleted when a stack is being released

- ci/create_codewind_index.py
If the index.yaml file has a `deprecated` element for a stack the generated codewind index json file need to have a similar element. This change adds the `deprecated` element to the json file.
> Update to add deprecated flag to codewind index json file

- ci/download_cli.sh
Update the fallback version for the appsody CLI to be the latest released version (0.6.1)
> Update CLI falback version to be latest version

- incubator/quarkus/README.md
I noticed that a few places the README page for Quarkus still referenced `experimental`, even though it had been moved to the `incubator`.
> Update README page for Quarkus

- ci/ext/pre_list.d/10_travis
Temporarily removes the `java-openliberty` stack from the default stacks list until problems reported in https://github.com/appsody/stacks/issues/799 are resolved.
> Temporarily remove java-openliberty from default stacks list

- incubator/quarkus/image/project/pom.xml
- incubator/quarkus/stack.yaml
- incubator/quarkus/templates/default/pom.xml
- incubator/quarkus/templates/kafka/pom.xml
The Quarkus stack does not include any metrics by default.
This PR adds the `quarkus-smallrye-metrics` dependency to `pom.xml` so that a basic set of metrics are automatically generated and hosted on `/metrics`.
The purpose of this is so that the default app is "Kubernetes ready" - in particular, so that the monitoring features in the Appsody Operator work: https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.md#Monitoring
> quarkus: add smallrye-metrics

- incubator/nodejs-express/README.md
- incubator/nodejs-express/image/project/package-lock.json
- incubator/nodejs-express/image/project/package.json
- incubator/nodejs-express/image/project/server.js
- incubator/nodejs-express/stack.yaml
It turns out that express-pino-logger just returns pino-http, so use it
directly, as is the current recommendations.
See:
- https://github.com/pinojs/pino/commit/3acca206f6cfa70fa20c6b1e7eee1311910ad671
- https://github.com/pinojs/express-pino-logger/blob/2b9bd6a551610a4ba4a6c0e42de94b3fe7804298/logger.js#L2
> nodejs-express: use pino-http directly

- incubator/java-openliberty/stack.yaml
- incubator/java-openliberty/templates/kafka/README.md
- incubator/java-openliberty/templates/kafka/pom.xml
- incubator/java-openliberty/templates/kafka/src/main/resources/META-INF/microprofile-config.properties
Fix `appsody stack validate` for java-openliberty kafka template.
`appsody test` was failing because the Liberty application did not start. This was because the kafka host specified in `microprofile-config.properties` was `kafka`, the correct hostname for use with the supplied `docker-compose.yaml`.  However, when running `stack validate`, the Docker compose environment wasn't there and therefore the host could not be resolved. 
To fix this I've set the default host for Kafka in `microprofile-config.properties` to be `localhost`.  This allows the Liberty app to start (even though it still won't connect to a Kafka) and therefore `appsody test` will pass during `stack validate`. 
This also means the default configuration is correct for host-mode develepment (`mvn liberty:dev`) so I've …
> java-openliberty: fix stack validate

- ci/ext/pre_list.d/10_travis
Adds the `java-openliberty` stack to the default stacks list as the problems in #799 has been resolved with the merge of #805 
Undoes: https://github.com/appsody/stacks/pull/803
> add java-openliberty to default stacks list

- incubator/quarkus/README.md
- incubator/quarkus/templates/kafka/README.md
As requested by @neeraj-laad I've added a specific README.md in the folder for the kafka template of the Quarkus stack.  This keeps the details out of the main README.md and makes it consist with the other stacks.
> Add README for Quarkus kafka template

- incubator/quarkus/image/config/app-deploy.yaml
- incubator/quarkus/image/project/pom.xml
- incubator/quarkus/stack.yaml
Add the `monitoring` section to `app-deploy.yaml`. This means that the Appsody Operator will autocreate a `ServiceMonitor` CR for consumption into Prometheus.
> quarkus: add monitoring to app-deploy.yaml

- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
When trying to do an `appsody build` using the java-openliberty stack in a GitHub Actions, CI environment, I hit the following error: 
```
[Docker] Step 18/68 : COPY --chown=1001:0 --from=compile /configlibdir/ /config
[Docker] failed to export image: failed to create image: failed to get layer sha256:27f55a0113aeec813a6bb31695fd2449c4dc13fe53adb7a67e144c325b63bdf7: layer does not exist
[Error] exit status 1
```
This appears to be caused by moby/moby#37965.  The characteristics of the `COPY` don't exactly match the description in the issue but the symptom is the same.    This issue has been open for a while and there's no sign of a fix so I think it's worth putting a workaround in the stack. I've added the suggested `RUN true`, which fixes the issue for me.  It seems like subsequent …
> java-openliberty: Work around docker bug

- incubator/python-flask/image/Dockerfile-stack
- incubator/python-flask/image/project/Dockerfile
- incubator/python-flask/stack.yaml
Avoid clashing UIDs in the attempt to ensure the application does not run as root. Since the Dockerfiles already create a non-root user, do not also set APPSODY_USER_RUN_AS_LOCAL to true.
Attempting to only use APPSODY_USER_RUN_AS_LOCAL=true and not create a user in the Dockerfile, leads to different issues regarding clashing UIDs
Fixes #833
> python-flask: Avoid permission errors when building dependencies

- experimental/rust-tide/README.md
- experimental/rust-tide/image/Dockerfile-stack
- experimental/rust-tide/image/project/Dockerfile
- experimental/rust-tide/image/project/server/bin/Cargo.toml
- experimental/rust-tide/image/project/server/bin/Dockerfile
- experimental/rust-tide/stack.yaml
- experimental/rust-tide/templates/default/Cargo.toml
- experimental/rust-tide/templates/default/src/lib.rs
Updates for the stack to keep in sync with upstream releases
tide has released 0.11
https://github.com/http-rs/tide/releases/tag/v0.11.0 
rust has released 1.44.0
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1440-2020-06-04
> rust-tide: Next tide and rust runtime releases

- incubator/nodejs-express/stack.yaml
- incubator/nodejs-express/templates/kafka/app.js
This PR illustrates how to avoid a hang when running the stack tests where the application makes connections to external services.
I have added a callback on the HTTP server `close` event, to disconnect the Kafka producer and consumer.  This allows the process to terminate normally.
Resolves #831
> nodejs-express: Shut down Kafka clients when HTTP server is closed

- incubator/nodejs-express/image/project/Dockerfile
- incubator/nodejs-express/stack.yaml
Installs the `ca-certificates` package when building the production image for an application based on the nodejs-express stack.  This is necessary because the base `node:12-slim` image does not include that package, and it is required in order for TLS certificate validation to work for any properly signed certificates.
Fixes #836
> nodejs-express: Install ca-certificates when building production image

- incubator/java-openliberty/README.md
- incubator/java-openliberty/stack.yaml
Update Open Liberty fix pack 20.0.0.3 => 20.0.0.6
> Upgrade java-openliberty stack to Open Liberty 20.0.0.6

- incubator/nodejs-express/README.md
The current nodejs-express stack can take a long time to build in some envs (cp4apps). adding some doc for possible workarounds.
> Add performance workaround to readme

- incubator/nodejs/README.md
- incubator/nodejs/image/Dockerfile-stack
- incubator/nodejs/image/project/Dockerfile
- incubator/nodejs/stack.yaml
I added `npm build` and `npm prune` steps to the build process for the production image, to provide a point of customization in cases where the project needs to perform build actions (such as running the Angular or Typescript compiler).
The 'prune' step is required to remove any development dependencies, and/or perform any cleanup of artifacts generated during the build, which would otherwise bloat the final image. 
Although there is an `npm prune` command, it does not behave the same way as `install`, `test` etc in that it does not invoke any scripts in package.json (none of `prune`, `preprune`, `postprune` are run).  The only way to run a script called `prune` is to run `npm run prune` (which is what I've gone for).  It is run with `--production` so that the user's script can invoke …
> nodejs: Add 'build' and 'prune' lifecycle events

- incubator/nodejs-express/stack.yaml
- incubator/nodejs-express/templates/kafka/README.md
The current readme doesn't show the user how to interact with the starter app.js so it could be quite confusing if they are new to kafka. I have added some new instructions for producing and consuming messages and restructured it a bit.
Fixes #848
> Add instructions for using starter app in nodejs-express Kafka template readme.

- incubator/java-openliberty/image/Dockerfile-stack
- incubator/java-openliberty/image/project/Dockerfile
- incubator/java-openliberty/stack.yaml
Update java-openliberty to 0.2.17 to pick up updates in base image (both stack image and appsody build image).
> Pull in kabanero/ubi8-maven:0.10.2
